### ISSUE TITLE
feature: change dummy text

### ISSUE THREAD

**Issue by SassNinja** [notwaldorf/font-style-matcher#18]
First of all: great tool! Good for working on FOUT issues :)

But one thing I'm really missing is a comfortable way (instead of the dev tools) to adjust the dummy text ('The fox jumped...').
So for example a textarea to define a custom dummy text.

This is really useful if optimizing a certain language or to test certain headlines.

@notwaldorf can such a feature be added?

**Comment by notwaldorf** [comment]
The text area at the bottom is editable, is that enough?

**Comment by SassNinja** [comment]
Oh, I didn't notice this – maybe a button or a hint would be helpful.
However this does the job so I'm closing this issue.
Thanks!
