### ISSUE TITLE
Applying styles to the fallback font

### ISSUE THREAD

**Issue by Jab2870** [notwaldorf/font-style-matcher#22]
Apologies if this is a stupid question but how do you apply styles that only get applied on the fallback font?

**Comment by notwaldorf** [comment]
you would have something like this for the fallback font:
```
div {
 font-family: Arial;
 font-weight: bold;
 letter-spacing: 1px;
}
```

And once you load your web font (you can use FontFaceObserver for this, for example), you can apply a custom class like `fonts-loaded`:
```
div.fonts-loaded {
 font-family: 'SomeCustomFamily';
 letter-spacing: 0;
}
```
